name: Live Stream
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install FFmpeg
        run: sudo apt update && sudo apt install ffmpeg -y
      - name: Start Stream
        env:
          STREAM_URL: ${{ secrets.STREAM_URL }}
          YOUTUBE_RTMP: ${{ secrets.YOUTUBE_RTMP }}
        run: python3 main.py
