name: Restream Seagull

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Tools (FFmpeg & yt-dlp)
        run: |
          sudo apt update
          sudo apt install ffmpeg -y
          pip3 install yt-dlp
          
      - name: Start Streaming
        run: python3 main.py
